server: 
   port: ${PORT:8761}
   servlet: 
    contextPath: /DiscoveryServer

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka: 
  client:
    registerWithEureka: false
    fetchRegistery: false

logging: 
  level:
     com: 
      netflix: 
       eureka: OFF
      discovery: OFF
