server: 
   port: ${PORT:8761}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka: 
  instance:
    hostname: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  client:
    registerWithEureka: false
    fetchRegistery: false

logging: 
  level:
     com: 
      netflix: 
       eureka: OFF
       discovery: OFF
