server: 
   port: ${PORT:8761}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka: 
  instance:
    hostname: grsdev-discovery-server.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistery: false

logging: 
  level:
     com: 
      netflix: 
       eureka: OFF
       discovery: OFF
