server: 
   port: ${PORT:8761}
   servlet: 
    contextPath: /DiscoveryServer

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka: 
  instance:
    hostname: grsdev-discovery-server.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistery: false
    serviceUrl:
      defaultZone: https://grsdev-discovery-server.herokuapp.com/DiscoveryServer

logging: 
  level:
     com: 
      netflix: 
       eureka: OFF
       discovery: OFF
