greetings:
   service:
     message: I am instance 1

server:  
  port: ${PORT:9001}
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true