greetings:
   service:
     message: I am running on

server:  
  port: ${PORT:9001}
  
info: 
 component: Greetings Service

management:
  endpoints:
    web:
     exposure:
       include: "*"
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown: 
    enabled: true
  
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
          
ribbon:
  eureka:
    enabled: true

spring:
    zipkin:
       baseUrl: http://localhost:9411
    sleuth:
       sampler:
          percentage: 1.0

sample:
   zipkin:
      enabled:true 
   