greetings:
   service:
     message: I am running on

server:  
  port: ${PORT:9001}
  
info: 
 component: Greetings Service

management:
  endpoints:
    web:
     exposure:
       include: "*"
 
  
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
          
ribbon:
  eureka:
    enabled: true