server:
 port: ${POST:8004}

info: 
 component: Gateway Server

management:
  endpoints:
    web:
     exposure:
       include: "*"
   
zuul:
 routes:
  greet:
   path: /greet/**
   serviceId: greet-service
   
ribbon:
  eureka: 
    enabled: true
  

eureka:
  client:
    serviceUrl:
      defaultZone: https://grsdev-discovery-server.herokuapp.com/DiscoveryServer/
    registerWithEureka: true