server:
 port: ${PORT:8009}

info: 
 component: Zipkin Server

management:
  endpoints:
    web:
     exposure:
       include: "*"
  
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2 